# Cheatsheet 3: Matrices

## Matrix Basics

### Creating Matrices

We can create a matrix using the `matrix` function. This a vector of data and either the number of rows/columns then fills the matrix column-wise.

In [3]:
X <- matrix(
    1:9,
    nrow = 3
)
X

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

We can alternatively fill by row by specifying `byrow = TRUE`.

In [6]:
Y <- matrix(
    c(1, 7, 2, 9, 4, 2),
    ncol = 2,
    byrow = TRUE
)

We can access the elements of a matrix using square brackets (like with vectors) containing two comma separated values. These correspond to the row and column index (`1, 1` is upper-left corner).

In [7]:
X[1, 2]

[1] 4

If we omit one of these indices, we instead get a vector containing the values of a column or row.

In [9]:
X[2, ]

[1] 2 5 8

In [10]:
X[, 2]

[1] 4 5 6

## Modifying Matrices

As with vectors, we can use `<-` with the two above facts to update an element or entire row/column.

In [11]:
X[2, 2] <- 0
X

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    0    8   
[3,] 3    6    9

We can also add a new column or row to a matrix by using the `cbind` and `rbind` functions (**c**olumn and **r**ow **bind**, respectively).

In [14]:
Z <- cbind(X, 1:3)
Z

[,1] [,2] [,3] [,4]
[1,] 1    4    7    1   
[2,] 2    0    8    2   
[3,] 3    6    9    3

## Matrix Algebra

### Matrix Arithmetic

The mathematical operators we saw before (`+`, `-`, `*`, `/`, `^`) also work on matrices. As with vectors, they will act element-wise, so require both matrices to be the same size.

In [16]:
X + X^2

[,1] [,2] [,3]
[1,]  2   20   56  
[2,]  6    0   72  
[3,] 12   42   90

It is important to note that this means that `*` and `^` represent element-wise multiplication and exponentiation, not standard matrix multiplication. To multiply matrices in the traditional way, we use the `%*%` operator instead.

In [18]:
X %*% Y

[,1] [,2]
[1,] 37   57  
[2,] 34   30  
[3,] 51   93

This requires the matrices to conform to each other.

In [19]:
Y %*% X

ERROR: Error in Y %*% X: non-conformable arguments


This operator also allows us to do matrix-vector multiplication. R will treat the vector as either a row or column vector depending on which is conforming.

In [22]:
X %*% c(1, 2, 3)

[,1]
[1,] 30  
[2,] 26  
[3,] 42

In [23]:
c(1, 2, 3) %*% X


[,1] [,2] [,3]
[1,] 14   22   50

### Linear Algebra

R is incredibly capable when it comes to performing linear algebra. One simple operation is transposition, performed using the `t` function.

In [20]:
t(Y)

[,1] [,2] [,3]
[1,] 1    2    4   
[2,] 7    9    2

We can invert a matrix using the `solve` function (this actually performs the more general function of solving any linear equation `Ax = b`—inversion is just the case when `b = I`; see the help page for more details).

In [21]:
solve(X)

[,1] [,2] [,3]      
[1,] -0.8  0.1  0.5333333
[2,]  0.1 -0.2  0.1000000
[3,]  0.2  0.1 -0.1333333